# Generated by Django 2.1.7 on 2019-03-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_clone', '0003_auto_20190330_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
